//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.15 at 03:11:24 AM WAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://sparkz.com/hrms", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sparkz.hrms;
